# Site settings
title: J Luo
email: jiahao.luo2014@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  个人博客。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jluo80.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: jluo80	
disqus: jluo80

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html
